---
- hosts: localhost
  vars_files:
    - vars/vars.yaml

  # List of tasks
  tasks:
    - name: launch an Ubuntu server

      # This lets us define an server
      os_server:
        cloud: "{{ cloud }}"
        # VM details
        state: present
        name: ansible_vm1
        image: Ubuntu-16.04
        flavor: 50
        key_name: "{{ key_name }}"
        network: public
        wait: yes
        meta:
          hostname: vm1
      register: ansible_vm1

    - name: get facts about the server (including its public v4 IP address)
      os_server_facts:
        cloud: dreamcompute
        server: ansible_vm1
      until: ansible_vm1.server.public_v4 != ""
      retries: 5
      delay: 10

    - set_fact: public_v4="{{ ansible_vm1.server.public_v4 }}"

    - name: add the server to our ansible inventory
      add_host: hostname={{ public_v4 }} groups=foo ansible_ssh_user=dhc-user ansible_ssh_private_key_file={{ private_key }}

    - name: pause and wait for sshd to start
      pause: seconds=15

- hosts: foo
  gather_facts: no
  tasks:
    - name: Install python2.7
      raw: "sudo apt-get update -qq && sudo apt-get install -qq python"
